CREATE TABLE PACIENTE (
RUT VARCHAR(20) PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
FECHA_NACIMIENTO  DATE

)
;



CREATE TABLE VACUNA (
NOMBRE_ENFERMEDAD VARCHAR(30) PRIMARY KEY NOT NULL,
FECHA_CREACION VARCHAR(30)
);



CREATE TABLE PACIENTE_RECIBE_VACUNA (
RUT VARCHAR(30) NOT NULL,
NOMBRE_ENFERMEDAD VARCHAR(30) NOT NULL,
FECHA_VACUNACION VARCHAR(30),
PRIMARY KEY (RUT,NOMBRE_ENFERMEDAD),
FOREIGN KEY (NOMBRE_ENFERMEDAD) REFERENCES VACUNA(NOMBRE_ENFERMEDAD)
);



INSERT INTO paciente(RUT,NOMBRE,FECHA_NACIMIENTO) VALUES('176177365','NATALIA SEPULVEDA','1991-11-04');


INSERT INTO VACUNA(NOMBRE_ENFERMEDAD,FECHA_CREACION) VALUES('INFLUENZA',CURRENT_TIMESTAMP);
INSERT INTO VACUNA(NOMBRE_ENFERMEDAD,FECHA_CREACION) VALUES('VARICELA',CURRENT_TIMESTAMP);

INSERT INTO PACIENTE_RECIBE_VACUNA(RUT,NOMBRE_ENFERMEDAD,FECHA_VACUNACION) VALUES('176177365','INFLUENZA',CURRENT_TIMESTAMP);

INSERT INTO paciente(RUT,NOMBRE,FECHA_NACIMIENTO) VALUES('176177360','NATALIO SEPULVEDO','1991-11-04');

